<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: idl/message.proto

namespace GPBMetadata\Idl;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
R
idl/message.protoPocMessaging.Protobuf"
Message
content (	BHbproto3'
        , true);

        static::$is_initialized = true;
    }
}

