<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace GPBMetadata;

class Message
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
v
message.protoPocMessaging.Protobuf"B
Message
content (	
smallNumber (
	bigNumber (BHbproto3'
        , true);

        static::$is_initialized = true;
    }
}

